data_paths: "BLUE_PEBBLE"  # Choose which paths version to use in PATHS
fcst_data_source: "ifs"
obs_data_source: "imerg"
normalisation_year: 2017
num_samples: 320000
normalise_inputs: True
output_normalisation: "log"
num_classes: 4 # Number of bins to split data into
min_latitude: -11.95
max_latitude: 15.05
latitude_step_size: 0.1
min_longitude: 25.05
max_longitude: 51.45
longitude_step_size: 0.1 ##ðŸš© The longitude step size is set to 2.8 for the NGCM data

##ðŸš© we need to change the input fields 
input_fields: 
    - 2t
    - cape
    - cp
    - r200
    - r700
    - r950
    - sp
    - t200
    - t700
    - tclw
    - tcwv
    - tisr
    - tp
    - u200
    - u700
    - v200
    - v700
    - w200
    - w500
    - w700
constant_fields:
    - orography
    - lsm
input_normalisation_strategy:
    tpq:
      negative_vals: False
      normalisation: "log"
    tp:
      negative_vals: False
      normalisation: "log"
    cp: 
      negative_vals: False
      normalisation: "log"
    pr:
      negative_vals: False
      normalisation: "log"
    prl:
      negative_vals: False
      normalisation: "log"
    prc:
      negative_vals: False
      normalisation: "log"
    sp:
      normalisation: "minmax"
    u: 
      normalisation: "max"
    v:
      normalisation: "max"
    w: 
      normalisation: "max"
    r:
      normalisation: "max"
    2t:
      normalisation: "minmax"
      negative_vals: False
    cape: 
      normalisation: "log"
    cin:
      normalisation: "max" 
    t:
      normalisation: "minmax"
      negative_vals: False
    tclw:
      normalisation: "log" 
    tcwv:
      normalisation: "max"
    tisr:
      normalisation: "max"

##ðŸš© NGCM input normalisation strategy

ngcm_input_normalisation_strategy:
    evaporation:
      normalisation: "log"
    precipitation_cumulative_mean:  
      negative_vals: False
      normalisation: "log"
    specific_cloud_ice_water_content:
      negative_vals: False
      normalisation: "log"
    u_component_of_wind:
      normalisation: "minmax"
    v_component_of_wind:
      normalisation: "minmax"
paths:
  BLUE_PEBBLE:
      GENERAL:
          IMERG: '/bp1/geog-tropical/users/uz22147/east_africa_data/IMERG/half_hourly/final/' ##ðŸš©IMERG data path need  also to be change and i need also to make sure that the 
          ERA5: '/bp1/geog-tropical/data/ERA-5/day'
          IFS: '/bp1/geog-tropical/users/uz22147/east_africa_data/IFS'
          OROGRAPHY: '/bp1/geog-tropical/users/uz22147/east_africa_data/constants/h_HRES_EAfrica.nc'
          LSM: '/bp1/geog-tropical/users/uz22147/east_africa_data/constants/lsm_HRES_EAfrica.nc'
          LAKES: '/bp1/geog-tropical/users/uz22147/east_africa_data/constants/lake_mask.nc'
          SEA: '/bp1/geog-tropical/users/uz22147/east_africa_data/constants/sea_mask.nc'
          CONSTANTS: '/bp1/geog-tropical/users/uz22147/east_africa_data/constants'
          NGCM: '/bp1/geog-tropical/users/uz22147/east_africa_data/NGCM' ##ðŸš©NGCM data is not yet available, so this is a placeholder for now.
          
      TFRecords:
          tfrecords_path: '/user/work/uz22147/tfrecords/'
